package jsonnet

import (
	"fmt"
	"log"
	"path/filepath"
	"sort"

	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/bitnami/jsonnet-gazelle/language/jsonnet/fileinfo"
)

const (
	dataImpPrivateAttr     = "_jsonnet_data_imports"
	jsonnetImpPrivateAttr  = "_jsonnet_imports"
	jsonnetSelfPrivateAttr = "_jsonnet_self"
)

// GenerateRules implements language.Language
func (l *Lang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	var res language.GenerateResult

	conf := GetConfig(args.Config)
	if conf.ShouldIgnoreFolder(args.Rel) {
		return res
	}

	// Generate map of existing files in the current package
	// to avoid iterating the array each time we want to check
	// if a file exists already.
	// NOTE: We know how many files the workspace contains, but
	// we don't know how much the workspace is going to grow.
	pkgFiles := map[string]bool{}
	for _, name := range args.RegularFiles {
		pkgFiles[filepath.Join(args.Rel, name)] = true
	}

	for _, name := range args.RegularFiles {
		if !conf.IsNativeImport(filepath.Ext(name)) {
			continue
		}
		finfo, err := NewFileInfo(args.Config, args.Dir, args.Rel, name, &Importer{l.Importer})
		if err != nil {
			log.Printf("%v", err)
			continue
		}
		if finfo == nil {
			continue
		}
		res.Gen = append(res.Gen, newLibraryRule(*finfo))
		res.Gen = append(res.Gen, newToJSONRule(*finfo, pkgFiles))
	}

	sort.SliceStable(res.Gen, func(i, j int) bool {
		return res.Gen[i].Name() < res.Gen[j].Name()
	})

	res.Imports = make([]interface{}, len(res.Gen))
	for i, r := range res.Gen {
		switch r.Kind() {
		case libraryRule:
			// The rule contains a private attribute with the imports
			// that we want to resolve back to deps in Resolve.
			res.Imports[i] = r.PrivateAttr(jsonnetImpPrivateAttr)
		case toJSONRule:
			// The rule contains a private attribute with the reference
			// to its own source file that we want to resolve back to
			// its deps in Resolve.
			res.Imports[i] = r.PrivateAttr(jsonnetSelfPrivateAttr)
		default:
			// To ensure len(res.Gen) == len(res.Imports)
			res.Imports[i] = nil
		}
	}

	return res
}

// https://github.com/bazelbuild/rules_jsonnet#user-content-jsonnet_library
//
// jsonnet_library
//
// This rule implementation will only generate rules with:
//
// name: 	[required] A unique name for this rule.
// srcs: 	[required] List of .jsonnet files that comprises this Jsonnet library.
// deps: 	<optional> List of targets that are required by the srcs Jsonnet files.
//
// This rule implementation will not generate (yet) rules with:
//
// imports: <optional> List of import -J flags to be passed to the jsonnet compiler.
func newLibraryRule(finfo fileinfo.FileInfo) *rule.Rule {
	name := finfo.Path.RuleName(libraryRulePrefix)
	r := rule.NewRule(libraryRule, name)
	r.SetAttr("srcs", []string{finfo.Path.Filename})
	r.SetAttr("visibility", []string{"//visibility:public"})

	// Mark jsonnet imports
	imports := make(map[string]fileinfo.FilePath, len(finfo.Imports))
	for imp, fpath := range finfo.Imports {
		imports[imp] = fpath
	}
	r.SetPrivateAttr(jsonnetImpPrivateAttr, imports)

	// Mark data imports
	dataImports := make(map[string]fileinfo.FilePath, len(finfo.DataImports))
	for imp, fpath := range finfo.DataImports {
		dataImports[imp] = fpath
	}
	r.SetPrivateAttr(dataImpPrivateAttr, dataImports)

	return r
}

// https://github.com/bazelbuild/rules_jsonnet#user-content-jsonnet_to_json
//
// jsonnet_to_json
//
// This rule implementation will only generate rules with:
//
// name:	[required]  A unique name for this rule.
// src:		[required]	The .jsonnet file to convert to JSON.
// outs:	[required]	Names of the output .json files to be generated by this rule.
// deps:	<optinoal>	List of targets that are required by the src Jsonnet file.
//
// This rule implementation will not generate (yet) rules with:
//
// multiple_outputs:	<optional>	Default: 0. Set to 1 to explicitly enable multiple file output
//									via the jsonnet -m flag.
// imports:				<optional>	List of import -J flags to be passed to the jsonnet compiler.
// stamp_keys:			<optional>	Specify which variables in ext_strs and ext_code should get stamped
//									by listing the matching dict keys.
// ext_strs:			<optional>	Map of strings to pass to jsonnet as external variables via --ext-str key=value.
// ext_str_envs:		<optional>	List of env var names containing strings to pass to jsonnet as external
//									variables via --ext-str key.
// ext_code:			<optional>	Map of code to pass to jsonnet as external variables via --ext-code key=value.
// ext_code_envs:		<optional>	List of env var names containing jsonnet code to pass to jsonnet as external
//									variables via --ext-code key.
// ext_str_files:		<optional>	(required for file_vars) List of string files that map to the var name defined
//									in file_vars at the same index and together are passed to jsonnet via --ext-str-file var=file.
// ext_str_file_vars: 	<optional>	(required for files) List of var names that maps to the file defined in files
//									at the same index and together are passed to jsonnet via --ext-str-file var=file.
// ext_code_files:		<optional>  List of jsonnet code files that map to the var name defined in ext_code_file_vars
//									at the same index and together are passed to jsonnet via --ext-code-file var=file.
// ext_code_file_vars:	<optional>  List of var names that maps to the code file defined in code_files at the same index
//									and together are passed to jsonnet via --ext-code-file var=file.
// tla_code_files:		<optional>	Dict of labels referencing code files and a var name, passed to jsonnet via --tla-code-file var=file.
// yaml_stream:			<optional>	Default: False. Set to 1 to write output as a YAML stream of JSON documents.
func newToJSONRule(finfo fileinfo.FileInfo, pkgFiles map[string]bool) *rule.Rule {
	name := finfo.Path.RuleName(toJSONRulePrefix)
	r := rule.NewRule(toJSONRule, name)
	r.SetAttr("src", finfo.Path.Filename)

	path := newOutput(finfo, ".json", pkgFiles)
	r.SetAttr("outs", []string{filepath.Base(path)})

	r.SetAttr("visibility", []string{"//visibility:public"})

	// We are generating jsonnet_library rules for each jsonnet file. Therefore,
	// we can use the file's own jsonnet_library rule as only dependency.
	r.SetPrivateAttr(jsonnetSelfPrivateAttr, map[string]fileinfo.FilePath{finfo.Path.Filename: finfo.Path})

	return r
}

// newOutput returns an output path for the given FileInfo and extension.
//
// If the output path already exists in the workspace or is an declared output of an existing rule,
// it generates a new name using <name>_X.<ext> format.
func newOutput(finfo fileinfo.FileInfo, ext string, pkgFiles map[string]bool) string {
	path := filepath.Join(finfo.Path.Package, finfo.Path.Name+ext)
	if _, found := pkgFiles[path]; !found {
		// Mark as used
		pkgFiles[path] = true
		return path
	}

	// There cannot be more than len(pkgFiles) files in the workspace
	// so we can safely assign a number [1,len(pkgFiles)+1]
	for i := 1; i <= len(pkgFiles)+1; i++ {
		path = filepath.Join(finfo.Path.Package, fmt.Sprintf("%s_%d%s", finfo.Path.Name, i, ext))
		// Mark as used
		if _, found := pkgFiles[path]; !found {
			pkgFiles[path] = true
			break
		}
	}

	return path
}
